"""
Seed the 57 tasks from the 123Dentist Excel spec.
Run once on startup if tasks table is empty.
"""

from db import SessionLocal, Task

TASKS = [
    # Phase 1 — Exhibit 1: Financial DD
    {
        "ref_id": "LD5",
        "name": "Employee schedule",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 1,
        "what_to_provide": "Tables summarizing each employee's role and compensation (wage rates, benefits). Separate tables for CDAs and other non-dentist staff.",
        "how_to_prepare": "Complete the employee schedule using the 123Dentist template provided by your onboarding contact. Return it by end of Week 1.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "LD6",
        "name": "Associate schedule",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 2,
        "what_to_provide": "Summary of each associate including payment rate, days/hours worked, sample monthly fee calculations, and associate agreements if available.",
        "how_to_prepare": "Complete the associate schedule template provided by 123Dentist. Include sample fee calculations. Return by end of Week 1.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "OD6a",
        "name": "Associate fee calculation examples",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 3,
        "what_to_provide": "Examples for each associate showing how fees are calculated including lab fee deductions.",
        "how_to_prepare": "Prepare one example per associate showing the calculation methodology. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD1",
        "name": "Financial statements",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 4,
        "what_to_provide": "Accountant-prepared financial statements for FY23 and FY24, monthly trial balances in Excel, general ledger detail, and a reconciliation where differences exist.",
        "how_to_prepare": "Provide to your accountant and request these documents. Upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD1 - Financial Statements",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD2",
        "name": "General ledger & trial balance data",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 5,
        "what_to_provide": "Detailed GL and trial balance for FY23, FY24, and trailing twelve months. Monthly trial balances and GL in Excel format.",
        "how_to_prepare": "Request from your accountant and upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD2 - GL & Trial Balance",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD3",
        "name": "Adjusting journal entries",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 6,
        "what_to_provide": "Year-end journal entries made by the accountant to reconcile GL/trial balance to final financials for FY23 and FY24.",
        "how_to_prepare": "Request from your accountant and upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD3 - Adjusting Journal Entries",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD4",
        "name": "Production & accounts receivable reports",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 7,
        "what_to_provide": "Production reports by provider, month, and procedure code. Aged AR reports as at Dec 2023 and Dec 2024. A final AR report is also required on the closing date.",
        "how_to_prepare": "Extract from your practice management software (your onboarding contact can assist). Upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD4 - Production & AR Reports",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD5",
        "name": "Payroll reports",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 8,
        "what_to_provide": "Monthly payroll reports by employee for FY23 and FY24. Payroll registers showing gross pay, CPP, EI, and deductions. Employee list with positions and employment agreements.",
        "how_to_prepare": "Request from your payroll provider and upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD5 - Payroll Reports",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD6",
        "name": "Production, collections & lab fees",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 9,
        "what_to_provide": "Monthly gross production, adjustments, collections, and lab fees by provider for FY23 and FY24.",
        "how_to_prepare": "Extract from your practice management software. Upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD6 - Production & Collections",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD7",
        "name": "Deferred revenue schedule",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 10,
        "what_to_provide": "A roll-forward of deferred revenue by practice at each historical period balance sheet date, where applicable.",
        "how_to_prepare": "Request from your accountant. Upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD7 - Deferred Revenue",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD8",
        "name": "Practice leases (financial review copy)",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 11,
        "what_to_provide": "Copies of all leases including amendments, and the most recent CAM statement.",
        "how_to_prepare": "Gather all signed lease documents and CAM statement. Upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD8 - Practice Leases",
        "due_week": "Week 1",
    },
    {
        "ref_id": "FD9",
        "name": "Management adjustments to EBITDA",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "Medium",
        "sort_order": 12,
        "what_to_provide": "A list of management-level financial adjustments (e.g. personal expenses in operating costs) with relevant GL detail.",
        "how_to_prepare": "Prepare with your accountant. Upload to the data room.",
        "data_room_path": "Financial Due Diligence > FD9 - EBITDA Adjustments",
        "due_week": "Week 2",
    },
    {
        "ref_id": "OD13",
        "name": "Supplies purchasing history",
        "phase": 1,
        "exhibit": "Financial Due Diligence",
        "priority": "High",
        "sort_order": 13,
        "what_to_provide": "SKU-level or summary data on supply purchasing history for the most recent 12 months.",
        "how_to_prepare": "Request a purchasing report from your dental supply vendors, or extract from your ordering system. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    # Phase 1 — Exhibit 2: Legal DD
    {
        "ref_id": "LD1",
        "name": "Shareholder IDs",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "High",
        "sort_order": 14,
        "what_to_provide": "Government-issued photo ID (e.g. driver's licence) for each shareholder.",
        "how_to_prepare": "Scan or photograph your government-issued ID. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD1 - IDs",
        "due_week": "Day 1",
    },
    {
        "ref_id": "LD2",
        "name": "Legal counsel contact information",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "High",
        "sort_order": 15,
        "what_to_provide": "Name, email address, and phone number of your legal counsel.",
        "how_to_prepare": "Contact your lawyer and confirm their details. Provide to your 123Dentist onboarding contact by Day 1.",
        "data_room_path": None,
        "due_week": "Day 1",
    },
    {
        "ref_id": "LD3",
        "name": "Minute books & corporate records",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "High",
        "sort_order": 16,
        "what_to_provide": "Articles of incorporation, minutes & resolutions, shareholder registers, share certificates, shareholders agreements, and identification of shares to be redeemed before closing.",
        "how_to_prepare": "Request from your corporate lawyer or accountant. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD3 - Minute Books",
        "due_week": "Week 1",
    },
    {
        "ref_id": "LD4",
        "name": "Contracts, agreements & consents",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "High",
        "sort_order": 17,
        "what_to_provide": "List of agreements requiring third-party consent for the transaction, and agreements that cannot be terminated on short notice.",
        "how_to_prepare": "Complete the Contracts Schedule template provided by Aird & Berlis. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD4 - Contracts",
        "due_week": "Week 1",
    },
    {
        "ref_id": "LD7",
        "name": "Financial statements (legal copy)",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "High",
        "sort_order": 18,
        "what_to_provide": "Accountant-prepared financial statements for the three most recent fiscal years — to be attached to the legal agreements.",
        "how_to_prepare": "Request from your accountant. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD7 - Financial Statements (Legal)",
        "due_week": "Week 1",
    },
    {
        "ref_id": "LD8",
        "name": "Debts & liabilities",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "High",
        "sort_order": 19,
        "what_to_provide": "Summary of all outstanding long-term debt including loan type, lender, and principal amount. Copies of any personal guarantees.",
        "how_to_prepare": "Gather loan statements and guarantee documents. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD8 - Debts & Liabilities",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD9",
        "name": "Corporate reorganization steps",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 20,
        "what_to_provide": "Pre-closing steps to prepare your corporation and shares for the transaction — to be discussed with your accountant.",
        "how_to_prepare": "Discuss with your accountant as soon as possible (Day 1). Draft reorg steps must be delivered to 123Dentist at least 2 weeks before closing. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD9 - Corporate Reorg",
        "due_week": "2 weeks before closing",
    },
    {
        "ref_id": "LD10",
        "name": "Work-in-progress (WIP) listing",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 21,
        "what_to_provide": "Patient-by-patient listing of ongoing dental procedures including amounts collected, associate fees paid, and estimated percentage of completion.",
        "how_to_prepare": "Complete using the LD10 - WIP template provided by your 123Dentist contact. Begin at least 3 weeks before closing. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD10 - WIP",
        "due_week": "3 weeks before closing",
    },
    {
        "ref_id": "LD11",
        "name": "Exhibit A — share/asset listing",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 22,
        "what_to_provide": "List of shares or assets being purchased by 123Dentist including classes, amounts, and purchase consideration.",
        "how_to_prepare": "Complete with your lawyer. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD11 - Exhibit A",
        "due_week": "2 weeks before closing",
    },
    {
        "ref_id": "LD12",
        "name": "Monthly production reports until closing",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 23,
        "what_to_provide": "Monthly production reports from your practice management software, covering each month from your most recent fiscal year-end through to closing.",
        "how_to_prepare": "Extract monthly from your practice management software. Upload to the data room monthly until closing.",
        "data_room_path": "Legal Due Diligence > LD12 - Monthly Production",
        "due_week": "Monthly until closing",
    },
    {
        "ref_id": "LD13",
        "name": "List of assets & excluded assets",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 24,
        "what_to_provide": "Detailed list of all clinic equipment, operatories, and assets included in the transaction, plus a list of excluded assets.",
        "how_to_prepare": "Complete using the LD13 - Equipment List template provided by your 123Dentist contact. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD13 - Assets",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD14",
        "name": "List of online assets",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 25,
        "what_to_provide": "List of all digital assets including websites, social media accounts, and phone/fax numbers.",
        "how_to_prepare": "Complete the Online Assets schedule provided by Aird & Berlis. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD14 - Online Assets",
        "due_week": "Week 2",
    },
    {
        "ref_id": "LD15",
        "name": "Intangibles & licensing agreements",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 26,
        "what_to_provide": "List of all patents, trademarks, copyrights, software, trade secrets, and any related licensing agreements.",
        "how_to_prepare": "Review with your lawyer. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD15 - Intangibles",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD16",
        "name": "Equipment licenses & leases",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 27,
        "what_to_provide": "Copies of all equipment licenses and leases, plus confirmation they will be paid out before closing.",
        "how_to_prepare": "Gather from your equipment finance providers. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD16 - Equipment Leases",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD17",
        "name": "Clinic permits",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 28,
        "what_to_provide": "Copies of all clinic permits (e.g. sedation, X-ray) and an accompanying list identifying each permit.",
        "how_to_prepare": "Gather copies of all active permits. Complete the Permits schedule provided by Aird & Berlis. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD17 - Permits",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD18",
        "name": "Principal dentist work schedule",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 29,
        "what_to_provide": "A weekly schedule showing the days and hours worked by the principal dentist(s).",
        "how_to_prepare": "Prepare a simple weekly schedule document and send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 2",
    },
    {
        "ref_id": "LD19",
        "name": "Tax filings — notices of assessment & T2",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 30,
        "what_to_provide": "Notices of assessment for the past 3 years and the most recent T2 corporate tax return filed with CRA.",
        "how_to_prepare": "Request from your accountant. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD19 - Tax Filings",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD20",
        "name": "Previous corporate names",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 31,
        "what_to_provide": "List of all previous names of the corporation and the dental practice.",
        "how_to_prepare": "Review with your lawyer or accountant. Send the list to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD21",
        "name": "Employee matters",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 32,
        "what_to_provide": "Workplace safety performance summary, any labour disputes or disciplinary actions, obligations to former employees, and related claims over the past 3 years.",
        "how_to_prepare": "Prepare with your HR advisor or lawyer. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD21 - Employee Matters",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD22",
        "name": "Claims & litigation",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Medium",
        "sort_order": 33,
        "what_to_provide": "List of any ongoing or anticipated legal disputes or regulatory investigations involving the clinic, dentists, or staff. Most recent professional inspection reports.",
        "how_to_prepare": "Prepare with your lawyer. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD22 - Claims & Litigation",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD23",
        "name": "Insurance policies & claims history",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Low",
        "sort_order": 34,
        "what_to_provide": "Copies of current insurance policies (property, liability, business interruption, etc.), claims history, and a table of major claims.",
        "how_to_prepare": "Request from your insurance broker. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD23 - Insurance",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD24",
        "name": "Data protection policies & AI tools",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Low",
        "sort_order": 35,
        "what_to_provide": "Copies of the clinic's patient data protection policies and a list of any software or AI tools currently used.",
        "how_to_prepare": "Locate your privacy policy documents and prepare a list of software/AI tools in use. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD24 - Data Protection",
        "due_week": "Week 3",
    },
    {
        "ref_id": "LD25",
        "name": "Closing AR report",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Low",
        "sort_order": 36,
        "what_to_provide": "An accounts receivable report produced on the closing date showing by-patient AR with aging buckets (Current, 30–60, 60–90, 90+ days).",
        "how_to_prepare": "Extract from your practice management software on the closing date. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD25 - Closing AR",
        "due_week": "Closing date",
    },
    {
        "ref_id": "LD26",
        "name": "Records of employment & vacation payout confirmation",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Low",
        "sort_order": 37,
        "what_to_provide": "Confirmation that ROEs have been issued to all staff, all vacation has been paid out, and no outstanding workers' compensation payments remain.",
        "how_to_prepare": "Confirm with your HR/payroll provider. Provide written confirmation to your 123Dentist onboarding contact on the closing date.",
        "data_room_path": None,
        "due_week": "Closing date",
    },
    {
        "ref_id": "LD27",
        "name": "Payout, discharge & no interest letters",
        "phase": 1,
        "exhibit": "Legal Due Diligence",
        "priority": "Low",
        "sort_order": 38,
        "what_to_provide": "Letters confirming all business debts have been cleared and that 123Dentist is acquiring a debt-free business.",
        "how_to_prepare": "Request from your lenders. Upload to the data room.",
        "data_room_path": "Legal Due Diligence > LD27 - Discharge Letters",
        "due_week": "Closing date",
    },
    # Phase 1 — Exhibit 3: Lease
    {
        "ref_id": "LS1",
        "name": "Landlord contact & permission to contact",
        "phase": 1,
        "exhibit": "Lease",
        "priority": "High",
        "sort_order": 39,
        "what_to_provide": "Name, email, and phone number of the clinic's landlord. Written permission for 123Dentist to contact the landlord directly.",
        "how_to_prepare": "Confirm landlord contact details and provide written consent. Send to your onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "LS2",
        "name": "Original lease agreement",
        "phase": 1,
        "exhibit": "Lease",
        "priority": "High",
        "sort_order": 40,
        "what_to_provide": "A copy of the fully signed original lease agreement for the business premises.",
        "how_to_prepare": "Locate your original signed lease and upload to the data room.",
        "data_room_path": "Lease > LS2 - Original Lease",
        "due_week": "Week 1",
    },
    {
        "ref_id": "LS3",
        "name": "Lease assignments",
        "phase": 1,
        "exhibit": "Lease",
        "priority": "High",
        "sort_order": 41,
        "what_to_provide": "Copies of all fully signed lease assignments derived from the original lease.",
        "how_to_prepare": "Locate all signed assignment documents and upload to the data room.",
        "data_room_path": "Lease > LS3 - Assignments",
        "due_week": "Week 1",
    },
    {
        "ref_id": "LS4",
        "name": "Lease amendments",
        "phase": 1,
        "exhibit": "Lease",
        "priority": "High",
        "sort_order": 42,
        "what_to_provide": "Copies of all fully signed amendments to the original lease agreement.",
        "how_to_prepare": "Locate all signed amendments and upload to the data room.",
        "data_room_path": "Lease > LS4 - Amendments",
        "due_week": "Week 1",
    },
    {
        "ref_id": "LS5",
        "name": "Real property ownership details",
        "phase": 1,
        "exhibit": "Lease",
        "priority": "High",
        "sort_order": 43,
        "what_to_provide": "Confirmation of whether the practice property is owned by the seller, and the relevant corporate structure.",
        "how_to_prepare": "Discuss with your accountant and/or lawyer. Provide a written confirmation to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "LS6",
        "name": "Triple-net lease cost invoices",
        "phase": 1,
        "exhibit": "Lease",
        "priority": "Medium",
        "sort_order": 44,
        "what_to_provide": "Invoices for regular upkeep and maintenance costs if the property is owned — CAM, utilities, and property taxes.",
        "how_to_prepare": "Gather recent invoices for these costs and send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 2",
    },
    # Phase 2 — Closing Day (TBD)
    {
        "ref_id": "CD1",
        "name": "IT system access handover",
        "phase": 2,
        "exhibit": "Closing Day",
        "priority": "High",
        "sort_order": 45,
        "is_tbd": True,
        "what_to_provide": None,
        "how_to_prepare": None,
        "data_room_path": None,
        "due_week": "Closing date",
    },
    {
        "ref_id": "CD2",
        "name": "Provider code activation",
        "phase": 2,
        "exhibit": "Closing Day",
        "priority": "High",
        "sort_order": 46,
        "is_tbd": True,
        "what_to_provide": None,
        "how_to_prepare": None,
        "data_room_path": None,
        "due_week": "Closing date",
    },
    {
        "ref_id": "CD3",
        "name": "Staff communications",
        "phase": 2,
        "exhibit": "Closing Day",
        "priority": "High",
        "sort_order": 47,
        "is_tbd": True,
        "what_to_provide": None,
        "how_to_prepare": None,
        "data_room_path": None,
        "due_week": "Closing date",
    },
    {
        "ref_id": "CD4",
        "name": "Banking & financial account setup",
        "phase": 2,
        "exhibit": "Closing Day",
        "priority": "High",
        "sort_order": 48,
        "is_tbd": True,
        "what_to_provide": None,
        "how_to_prepare": None,
        "data_room_path": None,
        "due_week": "Closing date",
    },
    {
        "ref_id": "CD5",
        "name": "Government & tax account authorizations",
        "phase": 2,
        "exhibit": "Closing Day",
        "priority": "High",
        "sort_order": 49,
        "is_tbd": True,
        "what_to_provide": None,
        "how_to_prepare": None,
        "data_room_path": None,
        "due_week": "Closing date",
    },
    {
        "ref_id": "CD6",
        "name": "Other closing-day actions",
        "phase": 2,
        "exhibit": "Closing Day",
        "priority": "High",
        "sort_order": 50,
        "is_tbd": True,
        "what_to_provide": None,
        "how_to_prepare": None,
        "data_room_path": None,
        "due_week": "Closing date",
    },
    # Phase 3 — Exhibit 4: Onboarding & Integration
    {
        "ref_id": "OD1",
        "name": "Sedation information",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "High",
        "sort_order": 51,
        "what_to_provide": "Details on the types and amounts of sedation offered at the practice.",
        "how_to_prepare": "Prepare a brief summary of your sedation capabilities. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Day 1",
    },
    {
        "ref_id": "OD2",
        "name": "Benefits package summary",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "High",
        "sort_order": 52,
        "what_to_provide": "A description of the current benefits plan including coverage details, eligibility criteria, premium allocation, RSPs, uniform allowances, health spending accounts, and professional dues.",
        "how_to_prepare": "Request a benefits summary from your current benefits provider. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "OD3",
        "name": "Recent benefits invoice",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "High",
        "sort_order": 53,
        "what_to_provide": "A recent invoice showing premium costs and the number of employees covered by the plan.",
        "how_to_prepare": "Request the most recent invoice from your benefits provider. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "OD4",
        "name": "Employee benefit listing",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "High",
        "sort_order": 54,
        "what_to_provide": "A list of all employees with benefit-relevant details: gender, date of birth, coverage type, and eligibility.",
        "how_to_prepare": "Complete using the OD4 - Benefits template provided by your 123Dentist contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "OD5",
        "name": "Payroll policies",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "High",
        "sort_order": 55,
        "what_to_provide": "Documentation of payroll-related policies including overtime, sick leave, vacation, holidays, and staff socials.",
        "how_to_prepare": "Gather your payroll policy documents. Send to your onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "OD6b",
        "name": "Associate fee calculation examples (post-close)",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "High",
        "sort_order": 56,
        "what_to_provide": "Examples for each associate showing how fees are calculated — for review by the 123Dentist finance team.",
        "how_to_prepare": "Prepare one calculation example per associate. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 1",
    },
    {
        "ref_id": "OD7",
        "name": "List of vendors & suppliers",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Medium",
        "sort_order": 57,
        "what_to_provide": "A list of all vendors and suppliers engaged with the business, noting whether formal contracts are in place.",
        "how_to_prepare": "Complete using the OD7 - Vendor List template provided by your 123Dentist contact. Send to your onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 3",
    },
    {
        "ref_id": "OD8",
        "name": "Employee manual",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Medium",
        "sort_order": 58,
        "what_to_provide": "A copy of the clinic's employee manual or office policy handbook, if one exists.",
        "how_to_prepare": "Send a copy to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 3",
    },
    {
        "ref_id": "OD9",
        "name": "Bank account information",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Medium",
        "sort_order": 59,
        "what_to_provide": "List of all business bank accounts including account numbers, financial institutions, and authorized signatories.",
        "how_to_prepare": "Gather your business banking details and send securely to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 3",
    },
    {
        "ref_id": "OD10",
        "name": "IT onboarding checklist",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Medium",
        "sort_order": 60,
        "what_to_provide": "Information on the clinic's current technology infrastructure including software and hardware.",
        "how_to_prepare": "Complete the OD10 - IT Onboarding Checklist provided by your 123Dentist contact. Send to your onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 2",
    },
    {
        "ref_id": "OD11",
        "name": "List of provider codes",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Medium",
        "sort_order": 61,
        "what_to_provide": "Provider codes currently used at the practice with corresponding provider details. These will be updated to new codes at closing.",
        "how_to_prepare": "Complete using the OD11 - Provider Code template provided by your 123Dentist contact. Send to your onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 3",
    },
    {
        "ref_id": "OD12",
        "name": "Government & tax account authorizations",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Low",
        "sort_order": 62,
        "what_to_provide": "Authorization for 123Dentist to be added as a filer for all CRA, provincial, and payroll tax accounts. Revocation of vendor's previous access.",
        "how_to_prepare": "Complete with your accountant. Required authorization forms will be provided by your 123Dentist contact.",
        "data_room_path": None,
        "due_week": "On or shortly after closing",
    },
    {
        "ref_id": "OD14",
        "name": "Key operating metrics",
        "phase": 3,
        "exhibit": "Onboarding & Integration",
        "priority": "Medium",
        "sort_order": 63,
        "what_to_provide": "Key performance data for the past 12 months: monthly new patient acquisition, capacity utilization %, referral volumes and types, and booking lead times.",
        "how_to_prepare": "Extract from your practice management software or prepare manually. Send to your 123Dentist onboarding contact.",
        "data_room_path": None,
        "due_week": "Week 3",
    },
]


def seed_tasks():
    db = SessionLocal()
    try:
        count = db.query(Task).count()
        if count > 0:
            print(f"[seed] Tasks already seeded ({count} tasks). Skipping.")
            return
        for t in TASKS:
            task = Task(
                ref_id=t["ref_id"],
                name=t["name"],
                phase=t["phase"],
                exhibit=t["exhibit"],
                priority=t["priority"],
                sort_order=t.get("sort_order", 0),
                is_tbd=t.get("is_tbd", False),
                what_to_provide=t.get("what_to_provide"),
                how_to_prepare=t.get("how_to_prepare"),
                data_room_path=t.get("data_room_path"),
                due_week=t.get("due_week"),
            )
            db.add(task)
        db.commit()
        print(f"[seed] Seeded {len(TASKS)} tasks.")
    except Exception as e:
        db.rollback()
        print(f"[seed] Error: {e}")
    finally:
        db.close()
